"""
This is a setup.py script generated by py2applet

reference: https://pythonhosted.org/py2app/

Usage:
    clean:     rm -rf build dist
    build: python setup.py py2app
    dev build: python setup.py py2app -A

    terminal run: ./dist/gs_scrambler.app/Contents/MacOS/gs_scrambler
    run: open -a dist/gs_scrambler.app & open -a Console
"""

from setuptools import setup

APP = ['gs_scrambler.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
